# Get orders
GET http://localhost:3000/orders
Content-Type: application/json
###

# Post order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "productId": 9 ,
    "quantity": 2
}
###

# Get order detail
GET http://localhost:3000/orders/:id
Content-Type: application/json

{
    "orderId":
}
###


# Remove an order
DELETE http://localhost:3000/orders/:id
Content-Type: application/json


{
    "orderId":3
}
###